name: Breakouts Analysis (Daily at 07:00 UTC)

on:
  schedule:
    # Run daily at 07:00 UTC
    - cron: '0 7 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  analyze_breakouts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Or consider updating to @v4 if compatible with other actions

    - name: Set up Python 3.12
      uses: actions/setup-python@v5 # Using latest stable version
      with:
        python-version: '3.12'

    # Removed the 'Setup uv' step

    - name: Install dependencies using pip and venv
      run: |
        python -m venv .venv          # Create a virtual environment
        source .venv/bin/activate     # Activate the virtual environment
        python -m pip install --upgrade pip # Upgrade pip within the venv
        pip install -r requirements.txt # Install dependencies from requirements.txt

    - name: Run breakouts analysis
      env:
        # Core Secrets (Required)
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MAX_COINS_TO_ANALYZE: ${{ vars.MAX_COINS_TO_ANALYZE || '50' }}

        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        MAX_COINS_TELEGRAM: ${{ vars.MAX_COINS_TELEGRAM || '10' }}

        # Optional Secrets (Needed for specific collectors)
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}

        ENABLE_KUCOIN_TA: ${{ vars.ENABLE_KUCOIN_TA || 'false' }}
        KUCOIN_API_KEY: ${{ secrets.KUCOIN_API_KEY }}
        KUCOIN_API_SECRET: ${{ secrets.KUCOIN_API_SECRET }}
        KUCOIN_API_PASSPHRASE: ${{ secrets.KUCOIN_API_PASSPHRASE }}

        CURRENT_ASSET_SHEET_ID: ${{ secrets.CURRENT_ASSET_SHEET_ID }}

        RSI_BUY_1D_THRESHOLD: ${{ vars.RSI_BUY_1D_THRESHOLD || '70' }}
        RSI_BUY_7D_THRESHOLD: ${{ vars.RSI_BUY_7D_THRESHOLD || '60' }}

        # Configuration Settings (Match .env.example)
        TOP_COINS_LIMIT: ${{ vars.TOP_COINS_LIMIT || '100' }}
        DEVELOPMENT_MODE: false
        SKIP_GPT: ${{ vars.SKIP_GPT || 'false' }}
        GPT_MODEL: ${{ vars.GPT_MODEL || 'gpt-5-nano' }}
      run: |
        source .venv/bin/activate    # Activate venv again for this step
        python run_breakouts.py             # Run the breakouts analysis script

    - name: Upload Excel file as artifact
      uses: actions/upload-artifact@v4 # Using latest stable version
      with:
        name: crypto-signals
        path: cryptos.xlsx