name: Daily Crypto Signal Analysis

on:
  schedule:
    # Run daily at 07:00 UTC
    - cron: '0 7 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Setup uv
      uses: astral-sh/setup-uv-action@v1
      
    - name: Install dependencies
      run: |
        uv venv --python 3.10
        uv pip install -r requirements.txt
        
    - name: Run analysis
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        TOP_COINS_LIMIT: 100
        TRENDING_COINS_LIMIT: 100
        DEVELOPMENT_MODE: false
        SKIP_GPT: false
        MAX_COINS: 10
      run: python run.py
      
    - name: Upload Excel file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: crypto-signals
        path: cryptos.xlsx
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add cryptos.xlsx
        git commit -m "Update crypto signals for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push 